builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Mac
      linux: Linux
      386: i386
      amd64: x86_64
    files:
      - README.md
      - LICENSE
      - scripts/*
brews:
  - tap:
      owner: suzaku
      name: homebrew-shonenjump
    folder: Formula
    homepage:  https://github.com/suzaku/shonenjump
    description: A faster way to change directory and improve command line productivity.
    test: |
      system "#{bin}/shonenjump -version"
    install: |-
      bin.install "shonenjump"
      path = prefix/"etc/profile.d"
      path.mkpath
      system "cp", "scripts/shonenjump.bash", path/"shonenjump.bash"
      system "cp", "scripts/shonenjump.zsh", path/"shonenjump.zsh"
      system "cp", "scripts/shonenjump.fish", path/"shonenjump.fish"
      zsh_completion.install "scripts/_j" => "_j"
      fish_completion.install "scripts/j.fish"
    caveats: |-
      If you are using Bash, add the following line to your ~/.bash_profile:

        [ -f #{etc}/profile.d/shonenjump.bash ] && . #{etc}/profile.d/shonenjump.bash

      If you are using Zsh, add the following line to your ~/.zshrc:

        [ -f #{etc}/profile.d/shonenjump.zsh ] && . #{etc}/profile.d/shonenjump.zsh

      If you are using Fish, add the following line to your ~/.config/fish/config.fish:

        [ -f #{etc}/profile.d/shonenjump.fish ]; and source #{etc}/profile.d/shonenjump.fish
