builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Mac
      linux: Linux
      386: i386
      amd64: x86_64
    files:
      - README.md
      - LICENSE
      - scripts/*
brews:
  - tap:
      owner: suzaku
      name: homebrew-shonenjump
    folder: Formula
    homepage:  https://github.com/suzaku/shonenjump
    description: A faster way to change directory and improve command line productivity.
    test: |
      system "#{bin}/shonenjump -version"
    install: |-
      bin.install "shonenjump"
      bash_completion.install "scripts/shonenjump.bash" => "j"
      zsh_completion.install "scripts/shonenjump.zsh" => "_j"
      fish_completion.install "scripts/shonenjump.fish"