name: create-octo-diagram

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  octo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: "ignore,.github"
